FROM mongodb/mongodb-community-server:5-focal

# Set environment variables, but what to? 
# Seems like something I would instead pass in from the cloud provider?
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=example